### ISSUE TITLE
My bet UI 

### ISSUE THREAD

**Issue by bilgeozturk** [forzzabet/ssrui#344]
Could you add the Bet Type : Type de Pari
in "My Bets" page

![image](https://user-images.githubusercontent.com/36878597/116534341-12230d00-a8eb-11eb-9d32-e39933d46f4d.png)

Mobilini de kontrol edelim eklerken.

**Comment by emrebaris-angular** [comment]
bet type bilgisi gelmiyor sanırım

**Comment by emrebaris-angular** [comment]
@yzylmz eksik sanırım bet type bilgisini de dönebilir misin?

**Comment by yzylmz** [comment]
@emrebaris-angular data getUserBetsByRaceId endpoint inden geliyor ve betType field ida var. gösterim için BetTypePipe ini da kullanabilirsin.

**Comment by emrebaris-angular** [comment]
![image](https://user-images.githubusercontent.com/67747038/116675879-faad5800-a9ae-11eb-91d5-1ba6c321eca5.png)

bu table a burdan getUserBetsByRaceId  data gelmiyor bunu içeride tekrar mı çağırıcaz?

**Comment by emrebaris-angular** [comment]
@yzylmz
