### ISSUE TITLE
Could follow the same styling (colors & UpperCase first letter) in Status from "Bets page"

### ISSUE THREAD

**Issue by bilgeozturk** [forzzabet/ssrui#355]
![image](https://user-images.githubusercontent.com/36878597/116666407-9769f880-a9a3-11eb-8ffd-c8d92308754d.png)
![image](https://user-images.githubusercontent.com/36878597/116666433-9df87000-a9a3-11eb-9d0a-18e64bdc9702.png)

**Comment by emrebaris-angular** [comment]
@bilgeozturk  bu table neredeydi bulamadım da?

**Comment by bilgeozturk** [comment]
https://forza-281113.ew.r.appspot.com/race/Great%20Britain/28-04-2021/Hove%20Evening/10455995 my bets kısmı
