### ISSUE TITLE
Quinella Issue:

### ISSUE THREAD

**Issue by bilgeozturk** [forzzabet/ssrui#358]
I placed a Quinella bet yesterday with All Horses in K column, it happens that there are 2 Non-Starters:
I should have a Refund of 11.5 Euro
11.5 Euro =  39 Euro - 27.5 Euro
Old Total Price Calculation - the New Coupon Total Price Calculation.

![image](https://user-images.githubusercontent.com/36878597/116666713-f596db80-a9a3-11eb-8295-3d739ffde759.png)
![image](https://user-images.githubusercontent.com/36878597/116666729-fb8cbc80-a9a3-11eb-8807-dddf5a8509c2.png)
![image](https://user-images.githubusercontent.com/36878597/116666750-021b3400-a9a4-11eb-980f-07024a1745cb.png)

**Comment by yzylmz** [comment]
@bilgeozturk kuponu kontrol ettim hesaplama dogru çalışmış fakat refund işlemini yapmamış. local olarak test ettim ve refund işlemini gerçekleştirdi. daha önce düzelttigim bi bug dan dolayı böyle bi hata oluştugunu düşünüyorum, o yüzden issue u kapatıyorum.
